title = "effect #8"
desc = "effect #8 by Infuse Project & Trinity (1999)"
cmdline = "archive/demo/effect.exe"
category = "demoscene"

[origin]
desc = "pouet.net"
url = "https://www.pouet.net/prod.php?which=17038"
