title = "Follow Me"
desc = "Follow Me by 2 Many People (2000)"
cmdline = "archive/demo/followme/fm_ddraw.exe"
category = "demoscene"
broken = true
status = "missing VirtualQuery"

[origin]
desc = "pouet.net"
url = "https://www.pouet.net/prod.php?which=3946"
