title = "Monolife"
desc = "Monolife by Hatha (1997)"
dir = "archive/demo/monolife/"
path = "monolife.exe"
files = ["monolife.dat"]
category = "demoscene"
status = "stuck on first scene, possibly audio related"

[origin]
desc = "pouet.net"
url = "https://www.pouet.net/prod.php?which=7698"
