title = "stream"
desc = "stream by mfx"
dir = "archive/demo/stream/"
path = "stream.exe"
category = "demoscene"
broken = true

[origin]
desc = "pouet.net"
url = "https://www.pouet.net/prod.php?which=1382"
