[workspace]
resolver = "2"
members = [
  "cli",
  "exe/no_std",
  "exe/rust",
  "exe/zip",
  "web/glue",
  "win32/derive",
]

[workspace.dependencies]
log = "0.4"
memory = { path = "memory" }
win32 = { path = "win32" }
x86 = { path = "x86" }
tsify = "0.4.1"
wasm-bindgen = "0.2.83"

[profile.lto]
inherits = "release"
lto = true
