[workspace]
members = [
  "cli",
  "web/glue",
  "win32/derive",
  "exe/ops-r",
]

[workspace.dependencies]
log = { path = "log" }
memory = { path = "memory" }
win32 = { path = "win32" }
x86 = { path = "x86" }

[profile.release]
lto = true
