[package]
name = "memory"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
serde_bytes = { version = "0.11.7", optional = true }

[features]
cpuemu = ["dep:serde", "dep:serde_bytes"]
