[package]
name = "gen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
syn = { version = "1.0", default-features = false, features = ["full", "parsing", "printing"] }
quote = "1.0"
proc-macro2 = "1.0"
