[package]
name = "retrowin32"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
win32 = { workspace = true }

anyhow = "1.0"
argh = "0.1.10"
libc = "0.2"

[dependencies.sdl2]
version = "0.35.2"
features = ["unsafe_textures"]
optional = true

[dependencies.iced-x86]
version = "1.17.0"
optional = true

[features]
sdl = ["dep:sdl2"]
cpuemu = ["dep:iced-x86", "win32/cpuemu"]
