category = "retrowin32 test"
title = "exit test"
desc = "tests exiting with status code"
cmdline = "local/target/i686-pc-windows-msvc/release/errors.exe exit"

[origin]
desc = "retrowin32"
url = "https://github.com/evmar/retrowin32/blob/main/exe/rust/src/bin/errors.rs"
