category = "retrowin32 test"
title = "gdi test"
desc = "empty window Rust GDI program"
cmdline = "local/target/i686-pc-windows-msvc/release/gdi.exe"

[origin]
desc = "retrowin32"
url = "https://github.com/evmar/retrowin32/blob/main/exe/rust/src/bin/gdi.rs"
