title = "zip/unzip round trip"
desc = "retrowin32's own performance test"
path = "local/target/i586-pc-windows-msvc/release/zip.exe"
cmdline = "zip.exe 1 zip.exe"
category = "retrowin32 test"

[origin]
desc = "retrowin32"
url = "https://github.com/evmar/retrowin32/tree/main/exe/zip"
