category = "retrowin32 test"
title = "zip/unzip round trip"
desc = "retrowin32's own performance test"
dir = "local/target/i586-pc-windows-msvc/release/"
cmdline = "zip.exe 1 zip.exe"

[origin]
desc = "retrowin32"
url = "https://github.com/evmar/retrowin32/tree/main/exe/zip"
