[package]
name = "win32"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
memory = { workspace = true }
win32-derive = { path = "derive" }
x86 = { workspace = true, optional = true }

anyhow = "1.0"
bitflags = "1.3.2"
num-derive = "0.3"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }
tsify = "0.4.1"
wasm-bindgen = "0.2.83"

[features]
x86-emu = ["dep:x86", "memory/x86-emu"]
