[package]
name = "win32"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bitflags = "1.3.2"
num-derive = "0.3"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }
tsify = "0.4.1"
wasm-bindgen = "0.2.83"

[dependencies.x86]
path = "../x86"
optional = true

[dependencies.log]
path = "../log"

[dependencies.memory]
path = "../memory"

[dependencies.win32-derive]
path = "derive"

[features]
cpuemu = ["dep:x86", "memory/cpuemu"]
