[package]
name = "zip"
version = "0.1.0"
build = "build.rs"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exe = { path = "../rust" }
miniz_oxide = "0.7.2"

[dependencies.windows-sys]
version = "0.52.0"
