[package]
name = "x86"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
iced-x86 = "1.17.0"
log = "0.4.17"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.7"
tsify = "0.4.1"
wasm-bindgen = "0.2.83"
