title = "DirectDraw spinning car"
desc = "simplest DirectDraw app"
path = "archive/BasicDD.exe"
category = "retrowin32 test"

[origin]
desc = "DirectDraw tutorial"
url = "https://www.codeproject.com/Articles/2370/Introduction-to-DirectDraw-and-Surface-Blitting"
