name: exe/ops test suite
on:
  push:
    paths:
      - 'exe/ops/ops.exe'
      - 'exe/ops/out.txt'
      - '.github/workflows/ops.yml'
    branches-ignore:
      - main
      - pages

defaults:
  run:
    shell: cmd

jobs:
  win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Run
        run: |
          cd exe\ops
          ops > new.txt
          diff --strip-trailing-cr -u out.txt new.txt
          move new.txt out.txt

      - name: Add results to PR
        run: |
          git config user.name "GitHub action"
          git config user.email "bot@github.com"
          git add exe
          git commit -m "update from CI"
          git push
